### ISSUE TITLE
UI can be enhanced using some library

### ISSUE THREAD

**Issue by ShivanshPlays** [TherkuTech/tturl#1]
I think the UI can be improved a bit @muruga21 @aswathcm29  I would be happy to work on it if you assign it to me.
![Screenshot 2024-10-01 174252](https://github.com/user-attachments/assets/6e145867-994b-41c2-82f5-ccd4debcc6e8)

**Comment by Sameeratweb** [comment]
We can enhance the UI by improving key elements such as background, text, user experience, and responsiveness.
I Would Like  to Work on it please assign me Labels.

 GSSoC'24-Extd | Contributor.

**Comment by muruga21** [comment]
@Sameeratweb Shivan was the first person to raise the issue on UI.. so im assigning it to him.. you can look to add any features to it...

**Comment by ShivanshPlays** [comment]
Okay, I'm on it

**Comment by ShivanshPlays** [comment]
Hi, @muruga21 Do you have any name in mind for the application? so that I can add it in the navBar

**Comment by muruga21** [comment]
@ShivanshPlays the application name will be TTURL, i will add the label soon

**Comment by ShivanshPlays** [comment]
Hi @muruga21, I have a humble request, could you please assign the tags: 
[gssoc-ext]
[hacktoberfest]
[hacktoberfest-accepted]
[level3]
to this issue, as I will be using aceternity UI to revamp and I think it is justified.
