### ISSUE TITLE
Add contact us page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TherkuTech/tturl#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
-  Add a contact us page which will give direct contact facitility to user to communicate us

**Describe alternatives you've considered**

**Additional context**

**Comment by muruga21** [comment]
@mehul-m-prajapati since this project is focused on single page useage.. im not planning to have a contact us page

**Comment by mehul-m-prajapati** [comment]
okay, thanks
