### ISSUE TITLE
In bottom adding contact and made by text 

### ISSUE THREAD

**Issue by Aditijainnn** [TherkuTech/tturl#14]
In the bottom of website adding contact us and made by text and adding github repo link and gmail or discord 
please assign this to me under gssoc exta and hacktoberfest

**Comment by muruga21** [comment]
@Aditijainnn yeah dude.. but i have different plan for the bottom.. if possible can you add a footer which has the list of contributors to this project.. you can use github api..

**Comment by Aditijainnn** [comment]
> @Aditijainnn yeah dude.. but i have different plan for the bottom.. if possible can you add a footer which has the list of contributors to this project.. you can use github api..

ok sure please assign this to me

**Comment by harish08102004** [comment]
Hey @muruga21 if no one is working on thus issue I can work on this.

**Comment by muruga21** [comment]
@Aditijainnn since it was 3 days.. im going to assign this task to @harish08102004 ...

**Comment by harish08102004** [comment]
Hey @muruga21 I have raised PR for the same.
