### ISSUE TITLE
making a feature to add it in as a chrome extension

### ISSUE THREAD

**Issue by Aditijainnn** [TherkuTech/tturl#15]
Adding a button(browse extension) in bottom as a download as your chrome extension and on clicking on that button they will be able to see it in chrome extension. But in this google developer account is neccsesary

**Comment by muruga21** [comment]
@Aditijainnn its a good idea but lets stick with the website right now

**Comment by Aditijainnn** [comment]
> @Aditijainnn its a good idea but lets stick with the website right now

ok no problem
