### ISSUE TITLE
Add dark/light mode feature

### ISSUE THREAD

**Issue by unknown91tech** [TherkuTech/tturl#16]
![image](https://github.com/user-attachments/assets/1e02d6da-0032-444d-a211-e63cc062b810)

Can create a better UI for this and add the dark mode feature on the page

@muruga21 can you assign this issue to me

**Comment by muruga21** [comment]
@unknown91tech please add dark mode and light mode.. no need to improve the ui, i have some other plans for it

**Comment by unknown91tech** [comment]
@muruga21 I have made a pr , can you review it and tell me if there are any changes to be made

**Comment by muruga21** [comment]
@unknown91tech i have merged the PR
