### ISSUE TITLE
Implement frontend of the short URL history feature 

### ISSUE THREAD

**Issue by samar12-rad** [TherkuTech/tturl#17]
Description:
@muruga21 
Currently, the URL shortening project lacks a frontend feature to display users' URL shortened history. The goal is to implement a user interface where users can view a list of their previously generated shortened URLs. This feature will enhance the user experience by allowing them to keep track of their shortened URLs in one place.

Proposed Solution:

1. Create a New History Page:

Develop a new page or section in the frontend that displays a table or list of all URLs the user has shortened.

The shortened URLs will be retrieved from local storage data stored on the user's browser.

2. Display Key Information:

Each entry in the history should display:

Original URL

Shortened URL

Date of creation

Option to copy the shortened URL

3. Add a history page navigation to the navbar . 
Addition of history page will generate a user flow and consistency separating functions of website to different locations.

4. Improve User Experience:

Add visual cues to highlight new entries or important actions, such as copying a URL.

Ensure the design follows the current style of the app for consistency.

Benefits:

Allows users to view and manage their shortened URLs in one place.

Enhances the functionality of the URL shortening service by making it more user-friendly and feature-rich.

Improves user retention by providing a history of activity within the app.

**Comment by samar12-rad** [comment]
@muruga21 , can you assign me this pls?

**Comment by muruga21** [comment]
@samar12-rad  no need to make additional page for history...

https://spotlight.thisux.com/

refer this dude..  and added the history section at bottom to the generate section

**Comment by samar12-rad** [comment]
ok

**Comment by muruga21** [comment]
@samar12-rad Hey samar are you working on this issue.. since im free today.. im plannig to work on it..? is it okay to you ?

**Comment by samar12-rad** [comment]
> @samar12-rad Hey samar are you working on this issue.. since im free today.. im plannig to work on it..? is it okay to you ?

I am working this @muruga21 .

**Comment by muruga21** [comment]
Yeah @samar12-rad .. can you send some images of what you have done.. so that i can give some insights

**Comment by samar12-rad** [comment]
Sorry, i was busy on other issues yesterday, I want to work it, please can you wait till today?  I took a look at the website you sent that day, and finalized a approach. 

A history array will be present which will load the histories on start. 


A use effect will run, whenever array is updated. 
In Use effect - 
 
The lastest generation will be extracted, and a function will run to create a card to show that url and old one, which will be added at the position.

**Comment by muruga21** [comment]
@samar12-rad Its fine dude.. if you are going to start now..

if you want to display the old url.. [ the urls of google forms might be lengthy.. displaying that inside a div might be harder ] so make sure you are using "truncate"...

the new link should be more highlighted [ more visible to increase the user experience ]

at the right you have to add a button called preview.. i can be a button or can be an icon.. if the user click the button it should open the respective urls in new tab 

![image](https://github.com/user-attachments/assets/e8be013b-6695-4932-9a2a-91e19ada8bca)

place the history bellow to the link generating section

if you have any doubts feel free to ping

**Comment by samar12-rad** [comment]
Ok got the idea from the pic you sent

**Comment by samar12-rad** [comment]
@muruga21 can you check my work?
