### ISSUE TITLE
Error Handling UI

### ISSUE THREAD

**Issue by ananyag309** [TherkuTech/tturl#18]
Instead of just displaying "Oops 404," consider implementing a more user-friendly error message along with an option to go back to the home page or try again.

**Comment by muruga21** [comment]
@ananyag309 yeah.. work on it

**Comment by muruga21** [comment]
@ananyag309 what the status of this issue.. it been more than a week..

**Comment by ananyag309** [comment]
will be done by today

**Comment by ananyag309** [comment]
i am sorry for being late was occupied by sem exam

**Comment by muruga21** [comment]
@ananyag309 yeah no worries.. thanks for your contribution
