### ISSUE TITLE
Can add Loading Spinner

### ISSUE THREAD

**Issue by ananyag309** [TherkuTech/tturl#19]
While the URL is being fetched, it's good to indicate to users that something is happening. You can show a spinner component during loading.

**Comment by muruga21** [comment]
![image](https://github.com/user-attachments/assets/b8462b35-f442-4fe1-8d43-b69dbda4ff62)
hey , @ananyag309  Im happy to see your enthusiasm to contribute.. but we are having spinner for the generate button right ?
