### ISSUE TITLE
Can Add or make more attractive UI

### ISSUE THREAD

**Issue by akashkumar241203** [TherkuTech/tturl#20]
Accessible Features: Ensure all elements are accessible for users with disabilities.
Interactive Elements: Add features like image carousels and hover effects on buttons for engagement.

**Comment by akashkumar241203** [comment]
Accessible Features: Ensure all elements are accessible for users with disabilities.
Interactive Elements: Add features like image carousels and hover effects on buttons for engagement.

**Comment by its-hafsa04** [comment]
I'm interested to resolve this issue please assign it to me

**Comment by muruga21** [comment]
@akashkumar241203 yeah akashkumar... i can see your interest in contributing to the project.. but right now, someone else is working on this.. if they are not able to complete this issue... i will assign it to you..
