### ISSUE TITLE
QR Code Generation

### ISSUE THREAD

**Issue by ananyag309** [TherkuTech/tturl#21]
Feature: Automatically generate a QR code for the shortened URL.
Implementation: Use a library like qrcode.react to create a QR code based on the generated URL.

**Comment by muruga21** [comment]
@ananyag309 Yeah.. Anayag this will be a great feature... But make sure you place the qr code in the right place... and convenient to the users

**Comment by coderKrysio** [comment]
hey @muruga21, is this issue still open?
I can work on this feature

**Comment by muruga21** [comment]
@coderKrysio yeah

**Comment by coderKrysio** [comment]
Hey @muruga21 
used a dummy link to generate the QR as the shortened URL function is not working properly in my local
check this out, and if you need any design modifications or changes let me know here
https://github.com/user-attachments/assets/80bfbdc8-dcf3-454f-a9a4-81af9acee989

**Comment by muruga21** [comment]
@coderKrysio Great work.. the ui needs some improvements..

![image](https://github.com/user-attachments/assets/553dd6fa-985f-4fd2-831d-4e8ac6e11030)

can you try to implement the ui like this.. and try to increase the popup size..

**Comment by coderKrysio** [comment]
Hey @muruga21 
Surely I will implement these changes , and will inform you shortly.

**Comment by coderKrysio** [comment]
Hey @muruga21,
made the changes
https://github.com/user-attachments/assets/6ee0831f-2bf6-4c1b-b13b-60d7f6761521
any further recommendations then let me know, otherwise I will create a PR

**Comment by coderKrysio** [comment]
> Hey @muruga21, made the changes https://github.com/user-attachments/assets/6ee0831f-2bf6-4c1b-b13b-60d7f6761521 any further recommendations then let me know, otherwise I will create a PR

hey @muruga21,
let me know your review for the changes mentioned above, so that I can make a pr for this

**Comment by muruga21** [comment]
@coderKrysio great work !

**Comment by muskiagrwal** [comment]
i want to work on this issue .assign me this project

**Comment by coderKrysio** [comment]
@muskiagrwal its already done and merged
