### ISSUE TITLE
HomePage UI is broken 

### ISSUE THREAD

**Issue by samar12-rad** [TherkuTech/tturl#23]
There is a white box apearing in the bottom out of nowhere, i think it is because of improper styling of frontend, can i fix the frontend? @muruga21 

![image](https://github.com/user-attachments/assets/522e6ae4-7f64-4d02-bf97-bde8625a11c7)

**Comment by muruga21** [comment]
@samar12-rad i too saw that.. i dont have much time to fix that.. could you do that.. 
and remove the header / navbar at the loading screen

![image](https://github.com/user-attachments/assets/8de38e42-b89f-485e-ae8e-bc0d9b364aa9)

**Comment by samar12-rad** [comment]
I will do that the most priority if you assign me that issue @muruga21

**Comment by samar12-rad** [comment]
Started work

**Comment by samar12-rad** [comment]
os the part you should with german words scrollable ? 
can you share a video ?

**Comment by samar12-rad** [comment]
@muruga21

**Comment by muruga21** [comment]
@samar12-rad its not about the scroll... when you click the generated link.. you can see hello in multiple languages right.. i that page i dont want header / navbar

**Comment by muruga21** [comment]
i hope im clear.. if not let me know

**Comment by samar12-rad** [comment]
let me check . 
Can you explain on clicking where does it happen?
As it is not happening on my side.
https://github.com/user-attachments/assets/c4109d16-9b36-4e50-9c6c-f9297c8600f8

**Comment by samar12-rad** [comment]
is it the loading?  i couldnt see that, because the loading is happening fast on my side. What changes do you want there ?

**Comment by muruga21** [comment]
@samar12-rad  in app/layout you can see Navbar component.. [ it makes the navbar global to all the pages ]  you have to remove that and in app/(default)/layout add the Navbar.. [ if makes navbar only for the home page ]

**Comment by samar12-rad** [comment]
> @samar12-rad  in app/layout you can see Navbar component.. [ it makes the navbar global to all the pages ]  you have to remove that and in app/(default)/layout add the Navbar.. [ if makes navbar only for the home page ]

Ok
