### ISSUE TITLE
[ADDING FOOTER] Adding Footer in a modern way to attract users and standout ✨

### ISSUE THREAD

**Issue by iamendless10** [TherkuTech/tturl#27]
Hello @muruga21 i would like to add footer in this project. Assign me this task under gssoc-ext and hacktoberfest so that i can start working immediately

**Comment by muruga21** [comment]
@iamendless10 some one is already working on the footer.. if they cant complete the work.. i will assign it to you.. i hope you understand.. 

Thanks
