### ISSUE TITLE
[BUG] : UI Broken 

### ISSUE THREAD

**Issue by Chandan-Kr-dev** [TherkuTech/tturl#28]
**Describe the bug**
The Home Page is broken and not fit to the screen 

**Expected behavior**
the home page should be on the complete screen size or there should a footer

i will add a very nice and eye-catching footer to the website  and handle the homepage breaking

**Comment by muruga21** [comment]
@Chandan-Kr-dev yup fix the ui.. make it as responsive.. no need to work on footer.. as some one is working on it..

**Comment by Chandan-Kr-dev** [comment]
Thank you for assigning me this issue, I will solve the issue and give a PR by today.

**Comment by muruga21** [comment]
@Chandan-Kr-dev i have close this... no need to work on it
