### ISSUE TITLE
Adding Header & Footer

### ISSUE THREAD

**Issue by Sameeratweb** [TherkuTech/tturl#3]
We can add a header and footer for improved responsiveness and better navigation.

**Comment by muruga21** [comment]
@Sameeratweb  dude you can added header and footer.. just tell me what you are gonna add on it.. since it is a single page application

**Comment by linga-007** [comment]
@muruga21 , I would like to contribute to this issue by adding header and footer to the website . In header , I would like to add a logo to your site  and in footer I would be adding your github profile , linkedin profile if possible and other common stuffs.

**Comment by muruga21** [comment]
@linga-007 work on this issue. you can find the logo in assets folder..  and for the footer is possible try to add number of stars, forks, and list of contributors.. else we can have it as new issue
