### ISSUE TITLE
Home , contact us , about us must add in navbar

### ISSUE THREAD

**Issue by Anjalis14** [TherkuTech/tturl#34]
**Is your feature request related to a problem? Please describe.**
on the navbar the essiential icon like home , contact us ets are not available

**Describe the solution you'd like**
I ll add the proper navbar for ur website which will enhance the website 

will add all type of icon in proper color format 
**Describe alternatives you've considered**
it is just an example
![image](https://github.com/user-attachments/assets/5ac952c0-74a4-47ea-ad9e-1a9b8438d3a2)

**Comment by Anjalis14** [comment]
@muruga21 plz assign me this

**Comment by muruga21** [comment]
@Anjalis14 I can see your interest for contribution in this repo.. but TTurl is a single page application, so i dont think having these elements is necessary.. you can look into other features or fix bugs in this repo.. I hope you understand

thanks
