### ISSUE TITLE
Creating About page 

### ISSUE THREAD

**Issue by Hh440** [TherkuTech/tturl#35]
creating the About page which gives the user an infomation about feature that the website provide and also the future insight.

Mission: A brief description of what our website aims to achieve.
Key Features: A summary of the main functionalities we offer.
User Benefits: How our platform helps and supports users.
Technologies: Highlighting the technology stack we use.
Security & Privacy: Information on how we ensure user data is safe.
Future Insights: A glimpse of upcoming features and plans for the platform.
![Screenshot from 2024-10-07 10-19-11](https://github.com/user-attachments/assets/cc00f684-4fb4-4807-b6d8-fab53e3f200b)

**Comment by muruga21** [comment]
@Hh440 This section is great.. from where did you got this design ?

**Comment by Hh440** [comment]
@muruga21 please assign so that i can start working on it

**Comment by muruga21** [comment]
@Hh440 yeah
