### ISSUE TITLE
Dockerize the Application 

### ISSUE THREAD

**Issue by PankajKumardev** [TherkuTech/tturl#39]
I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

[x ] I am contributing under GSSoC-ext
[x ] I am contributing under hacktoberfest
[x ] I follow contribution guidelines

**Comment by muruga21** [comment]
@PankajKumardev Hey.. I can see your interest in contribution to this repo.. but right now i feel we dont want to dockerize this application.. i hope you understand..

Thanks

**Comment by PankajKumardev** [comment]
ok
