### ISSUE TITLE
Enhance User Experience with URL Shortening Feedback

### ISSUE THREAD

**Issue by samar12-rad** [TherkuTech/tturl#4]
I would like to suggest an enhancement to improve the user experience for the URL shortening feature. Currently, after a user shortens a URL, the shortened URL is displayed in a box. However, it can be easy for users to miss this information.

Proposed Solution:

Add an alert box or toast notification that clearly states, "Your shortened URL is: [shortened URL]" to immediately grab the user's attention.
Highlight the box containing the shortened URL to make it stand out, improving user recognition and ensuring the shortened URL is more noticeable.
This change will make the feature more user-friendly and ensure the shortened URL is easily identified by the user.

**Comment by muruga21** [comment]
@samar12-rad please add a toast message that says, "Your URL has been shortened successfully." You can use react-hot-toast, which is already included in this project.

**Comment by vidhvath28** [comment]
Hi @muruga21,

I’m interested in working on this enhancement to improve the user experience for the URL shortening feature. I believe adding a toast notification and highlighting the shortened URL box will significantly benefit users.

Proposed Approach:

Implement a Toast Notification: I will use react-hot-toast to display a message that says, "Your URL has been shortened successfully," immediately after a user shortens their URL.
Highlight the Shortened URL Box: I will apply CSS styles to highlight the box containing the shortened URL, making it stand out visually to users.
Could I please be assigned to this issue? I look forward to implementing these changes!

Thank you!

**Comment by muruga21** [comment]
@vidhvath28 Hi Vidhvanth, I appreciate your interest in contributing to this project! Since I have assigned this issue to @samar12-rad, let’s wait until this evening to see if it gets resolved. If it’s still open by then, I’ll assign it to you. 

Thank you for your understanding!
