### ISSUE TITLE
Redirection Issue with URL Shortener

### ISSUE THREAD

**Issue by KumarAmrendram** [TherkuTech/tturl#40]
**Description**
When any URL prefixed with www (e.g., www.google.com) is shortened, the app incorrectly redirects to a URL with a duplicated prefix (e.g., www.www.google.com). This results in broken links and affects all URLs entered with the www prefix.

**To Reproduce**
    1. Open the URL shortener web app in Internet Explorer.
    2. Enter the URL www.google.com in the input field.
    3. Click on the "Shorten" button.
    
**Shortened URL:** https://tturl.netlify.app/3oy9uo1

**Expected behavior**
The shortened URL should redirect to www.google.com.

**Actual Behavior**
The app redirects to www.www.google.com, resulting in a broken link.

**Screenshots**
<img width="841" alt="Screenshot 2024-10-07 at 9 18 40 PM" src="https://github.com/user-attachments/assets/b9d713ac-ac7b-4c4d-bfee-80d4a3221836">

**Desktop:**
 - OS: Mac Os
 - Browser: Chrome
 - Version: Sonoma 14.5
 
 I would like to resolve this issue as part of my contributions for GSoC 24.

**Comment by muruga21** [comment]
@KumarAmrendram Yeah Kumar.. Thanks for finding this issue.. please work on it..
