### ISSUE TITLE
cache issue / header issue in dark mode

### ISSUE THREAD

**Issue by Sehrishzarin** [TherkuTech/tturl#41]
When you load the website the first time this is how it looks automatically 
![image](https://github.com/user-attachments/assets/99e594c8-1524-4e81-b105-f2da4c73a9cc)
but when you turn off and on dark mode it changes to normal and works fine even after reloads 
![image](https://github.com/user-attachments/assets/e8143b13-7d86-4748-8430-dab457ef4bd3)

**Comment by muruga21** [comment]
@Sehrishzarin Yeah dude.. are you going to work on this issue.. should i assign it to you ?

**Comment by Sehrishzarin** [comment]
I'd love to
