### ISSUE TITLE
Add Custom Slug Support for URL Shortening

### ISSUE THREAD

**Issue by adityakalburgi** [TherkuTech/tturl#44]
Currently, the application generates random shortened URLs for users. We want to enhance the user experience by adding support for custom slugs, allowing users to specify their own short URL alias instead of relying on a randomly generated one.
Expected Behavior:
1. Users can shorten URLs with custom slugs.
2. If no custom slug is provided, a random one will be generated.
3. Users are notified of any errors.
please assign this issue to me and i will do it for you and also add gssoc-ext labels..

**Comment by muruga21** [comment]
@adityakalburgi Yeah creating a custom url will be a great feature...but right now one of the contributor is working on implementing hashing algorithm.. so let us wait until he raise pr.. and i think we can focus on this feature after that..
i will assign this issue to you once that pr is merged..

i hope you understand..

Thanks
