### ISSUE TITLE
Can change the color of the paragraphs

### ISSUE THREAD

**Issue by STXRSHIVA** [TherkuTech/tturl#47]
we can change the color of the paragraphs , they are not at all visible 

https://github.com/user-attachments/assets/aea7c99f-1023-4665-a452-286b1df673fa

**Comment by muruga21** [comment]
@STXRSHIVA can you check with different browser... since i can see the text 
![image](https://github.com/user-attachments/assets/d43807bb-1726-4b90-8cd6-bc45d6277a7e)

**Comment by muruga21** [comment]
@STXRSHIVA this is happening due to improper state change in light mode and dark mode i guess.. are you ready to work on this issue.. shall i assign it to you ?

**Comment by STXRSHIVA** [comment]
okay please i'll work on this

**Comment by muruga21** [comment]
@STXRSHIVA whats it the status of this issue dude.. ?

**Comment by STXRSHIVA** [comment]
It's already merged

**Comment by muruga21** [comment]
@STXRSHIVA okay dude.. thanks for your contribution
