### ISSUE TITLE
Implement Missing Meta Tags, Generate Sitemap, and Create robots.txt for SEO Improvement

### ISSUE THREAD

**Issue by myselfshivams** [TherkuTech/tturl#5]
The current website is missing several crucial meta tags that are essential for search engine optimization (SEO). Additionally, we need to generate a sitemap and create a robots.txt file to enhance the site's visibility and crawling efficiency for search engines.

#### Add Missing Meta Tags:

- Title tags
-  Description tags
- Keywords tags
- Open Graph tags for social media sharing
- Robots meta tag
- Generate Sitemap:

#### Create an XML sitemap that includes all relevant pages of the website to facilitate better indexing by search engines.
Create robots.txt File:

#### Implement a robots.txt file to guide search engine crawlers on which pages to index and which to avoid.

Labels:
- GSSoC
- Hacktoberfest

Assignment:
- Please assign this issue to @myselfshivams.

**Comment by muruga21** [comment]
@myselfshivams please add the necessary tags and a robots.txt file. The tags should read: "TTURL - One Click URL Shortener."

**Comment by myselfshivams** [comment]
Hi @muruga21,

Thanks for the feedback! I’ll add the necessary meta tags, including the title "TTURL - One Click URL Shortener," as well as create the robots.txt file and generate the sitemap. I’ll keep you updated on my progress.

Let me know if you have any additional requirements!

Best,
@myselfshivams
