### ISSUE TITLE
Give a option to clear history of Urls

### ISSUE THREAD

**Issue by AyushSharma72** [TherkuTech/tturl#50]
i Want to add a button which let the user to clear the history of the urls 

please assign this issue to me @muruga21

**Comment by muruga21** [comment]
@AyushSharma72 Yeah ayush.. it would be a nice option..

**Comment by muruga21** [comment]
@AyushSharma72  Do you want to work on this issue ?

**Comment by AyushSharma72** [comment]
> @AyushSharma72 Do you want to work on this issue ?

yes ofcourse assign this to me @muruga21
