### ISSUE TITLE
[BUG FIX] The Font on the homepage is initially not visible when the site is loaded ✨

### ISSUE THREAD

**Issue by iamendless10** [TherkuTech/tturl#55]
hello9 @muruga21 i wish to fix this bug on your project please assign me this issue under gssoc-ext and hactoberfest level2 so that i can start working immediately

**Comment by muruga21** [comment]
@iamendless10 Yeah dude..

**Comment by muruga21** [comment]
@iamendless10 thanks for your contribution dude
