### ISSUE TITLE
Improve the UI of the page

### ISSUE THREAD

**Issue by jayanththalla** [TherkuTech/tturl#6]
The UI is not looking good adding  the symbols and icons
![image](https://github.com/user-attachments/assets/c2cabcea-0d19-4e27-aa66-a3a51e966ebf)

**Comment by muruga21** [comment]
@jayanththalla  Hey Jayanth, it’s great to see your enthusiasm for contributing to this project! However, I wanted to let you know that someone has already raised an issue regarding the UI, and they are currently working on it.

Let us give a chance to them them.. you can try to add new features..

**Comment by jayanththalla** [comment]
> @jayanththalla Hey Jayanth, it’s great to see your enthusiasm for contributing to this project! However, I wanted to let you know that someone has already raised an issue regarding the UI, and they are currently working on it.
> 
> Let us give a chance to them them.. you can try to add new features..
> 
> Thanks

Can I add the logo to the page

**Comment by muruga21** [comment]
yup @jayanththalla .. add logo in assets.. i will help to those making header.. and add a favicon for the application
