### ISSUE TITLE
change the black/dark mode & in header can make great logo 

### ISSUE THREAD

**Issue by REHAN-18** [TherkuTech/tturl#60]
hello9 @muruga21 i wish to fix this  on your project please assign me this issue under gssoc-ext and hactoberfest level2 so that i can start working immediately.
 in this Your shortened URL is not looking great in dark mode  & change the dark/light mode button should look  great & TTURL
logo I make better logo than this  pls assign me..
![Uploading Screenshot 2024-10-12 at 12.23.27 AM.png…]()

**Comment by muruga21** [comment]
@REHAN-18 yeah work on it

**Comment by REHAN-18** [comment]
ok sure 😇

**Comment by REHAN-18** [comment]
bro work done !!!!
<img width="1440" alt="Screenshot 2024-10-14 at 4 28 36 PM" src="https://github.com/user-attachments/assets/136aeb38-7c39-43ba-85c9-43272d14eb82">
changed the theme Switcher button now is looks great ..

**Comment by REHAN-18** [comment]
merge my pull request !! I have created a ui branch in this I have push the code....

**Comment by muruga21** [comment]
@REHAN-18 thanks for your contribution

**Comment by REHAN-18** [comment]
WELCOME
