### ISSUE TITLE
fix/Spinner is not aligned properly

### ISSUE THREAD

**Issue by anmolyadav-dev** [TherkuTech/tturl#61]
The current loading spinner is bigger in size and a little off alignment

![Screenshot 2024-10-12 010048](https://github.com/user-attachments/assets/2c4c15b9-c30b-4314-984a-c5e939a7096c)

After Fixing  it would look like this

https://github.com/user-attachments/assets/ab5add92-f32e-4dc9-a092-5a2bf22c9e51

kindly give me this issue under hacktoberfest2024 and gssoc-extd

**Comment by mauryavinay1407** [comment]
Heyy @anmolyadav-dev 

Could you please add the 'hacktoberfest-accepted' label to this PR because I forgot to add it.

**Comment by anmolyadav-dev** [comment]
I don't have option to add labels. Only you can add

**Comment by mauryavinay1407** [comment]
@anmolyadav-dev No worries about label , feel free to review and merge it.
