### ISSUE TITLE
Need of Dockerfile for Project Containerization and Deployment.

### ISSUE THREAD

**Issue by Suraj-kumar00** [TherkuTech/tturl#66]
### Description:
It is frustrating to setup the local development environment for everyone so...

We need to containerize our project for easier deployment and consistency across various environments. The Dockerfile should include the necessary configurations to build and run our application in a Docker container.

I would like to work on this issue as I'm proficient in `Cloud/DevOps` practices. I can:
1. Dockerize the project. 
2. Dockerize the project with `minimal docker image`.
3. Can Create a workflow to `build` and `push` the docker images to the `DockerHub Account` but for this I will need the credentials of your dockerhub account to push to docker image on your account.

Please assign this issue to me so that I can work on it.

**Comment by muruga21** [comment]
@Suraj-kumar00 right now i feel docker is not required.. and im planning to move the database form mongodb to postgresql.. so right now i cant assign this issue to you..

i hope you understand 

thanks
