### ISSUE TITLE
New Feature: Similar to Linktree

### ISSUE THREAD

**Issue by psr-codes** [TherkuTech/tturl#67]
**Is your feature request related to a problem? Please describe.**
It’s inconvenient to share multiple links using the current URL shortener, as it only supports single URLs. Users often need a single link that consolidates several URLs, like social profiles or websites.

**Describe the solution you'd like**
I propose adding a Linktree-like feature, allowing users to create a single, short link that opens a landing page containing multiple links. This would simplify sharing multiple resources through one short URL.

**Describe alternatives you've considered**
An alternative could be organizing links into folders, but that still requires sharing multiple links individually. A single link to a landing page is more efficient.

**Additional context**
This feature would appeal to users who need to share several URLs  to their social media, websites, blogs, enhancing the tool’s versatility and user-friendliness.
![{A3AEBACD-CA00-48E2-8B7A-074F4571A2F1}](https://github.com/user-attachments/assets/0a93925c-592d-40a4-a143-957ef718a45c)

**(expected level - 3)**

**Comment by muruga21** [comment]
@psr-codes I can see your interest in contribution to this issue.. it will be a great feature.. but this is beyond the projects scope.. and right now we are planning to some additional features.. you can look to fix bugs or try to add any other features .. 

i hope you understand

thanks
