### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by Bhum-ika** [TherkuTech/tturl#70]
**Describe the bug**
The navbar while scrolling is not fixed, it is moving and also the bg color should be different to create a difference 

**Expected behavior**
It should be fixed and I will enhance the UI of navbar

**Screenshots**

https://github.com/user-attachments/assets/5b550b70-9a73-43cb-8da7-d820ce02e8e6

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Redmi 12 5G

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by muruga21** [comment]
@Bhum-ika the nav bar should not be fixed.. as per our design.. and yeah you can work on nav bar color.. make sure you add the colors which match to the theme

**Comment by Bhum-ika** [comment]
Sure
