### ISSUE TITLE
Feature Request: Store and Display Shortened URL History

### ISSUE THREAD

**Issue by samar12-rad** [TherkuTech/tturl#8]
Hi @muruga21!, it was great working on the first issue. I would like to propose a new feature that allows users to view their history of shortened URLs. This feature will enhance user experience by providing easy access to previously generated links.

Proposed Implementation:

Functionality:
Users will be able to view a list of their shortened URLs generated during their session.
The shortened URL history will be stored in cookie data, allowing users to retrieve their previous links even after refreshing the page or closing the browser.

Acceptance Criteria:
Store Shortened URLs: Each time a user generates a shortened URL, it should be stored in cookies.
Display History:

A dedicated section on the application where users can see their shortened URLs.
Each entry should display the shortened URL and possibly the original URL for reference.

Benefits:
This feature will help users manage their shortened links effectively.
It improves overall user experience by providing a quick way to access previously generated URLs.

**Comment by muruga21** [comment]
@samar12-rad it will be a great feature.. but to store history of a particular user we must have a attribute "User" right.. we need to add login and sign up, to get user details. Only then we can store their history.. And I dont want to have such things..

**Comment by muruga21** [comment]
And if you want to work on the feature.. I can assign it to you

**Comment by samar12-rad** [comment]
Thank you @muruga21 , assign it to me, I will start working on it, as it is a complete new feature for the website.

**Comment by samar12-rad** [comment]
Thank you @muruga21 , assign it to me, I will start working on it, as it is a complete new feature for the website.

**Comment by muruga21** [comment]
@samar12-rad work on it.. Save the history in local storage

**Comment by muruga21** [comment]
@samar12-rad if you are facing any problem or you need any help.. please let me know

**Comment by samar12-rad** [comment]
No problems currently. I had yesterday. I will push it by today evening. If I get any problems, I will ping you .
