### ISSUE TITLE
Shortened Now button should appear after entered URL

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TherkuTech/tturl#83]
**Describe the bug**
If you paste long URL string, it gets hidden under Shortened Now button.

**To Reproduce**
1. Go to home page
2. Go text box and type long URL

**Expected behavior**
Shortened URL button should appear after entered URL

**Screenshots**
![tt1](https://github.com/user-attachments/assets/a69ded11-3879-4409-906c-cd8c968d590c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
na

**Comment by muruga21** [comment]
@mehul-m-prajapati yeah man.. when there is not url entered make the button disabled change its color.. after the user entered the url enable the button.. not to hide the button from the ui
