### ISSUE TITLE
Same text at two places in home page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [TherkuTech/tturl#84]
**Describe the bug**
Same text at two places in home page

**To Reproduce**
1. Go to home page
2. See error

**Expected behavior**
- First text should be: Paste the URL to be shortened
- Second text should be: Your shortened URL:

**Screenshots**
![tt2](https://github.com/user-attachments/assets/258ccd90-e68e-42da-a677-bcd5fbea51df)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muruga21** [comment]
@mehul-m-prajapati yeah work on it

**Comment by mehul-m-prajapati** [comment]
@muruga21 : please re assign
