### ISSUE TITLE
 Enhance UI with 3D Background, Header & Footer, and Animations

### ISSUE THREAD

**Issue by Mallik-vinukonda** [TherkuTech/tturl#90]
I noticed that the URL shortener repository could benefit from some visual improvements, particularly in the background, header, and footer sections. I'd like to enhance the design by adding a 3D background using Three.js, along with a clean and consistent header and footer. Additionally, I will incorporate smooth animations with GSAP to improve user interaction and create a more dynamic experience.

Let me know if you're open to these changes or if there are any specific design elements you'd like to see.

**Comment by muruga21** [comment]
@Mallik-vinukonda hey malik i can see your interest to contribution on this repo.. but right now my designer is making a minimal design for this project.. once the design is over i will assign this task with you..

i hope you can understand

thanks
