### ISSUE TITLE
Fix Scrolling on history page 

### ISSUE THREAD

**Issue by shubhagarwal1** [TherkuTech/tturl#96]
Allow users to set passwords on shortened URLs, restricting access to only those with the password.

**Comment by muruga21** [comment]
@shubhagarwal1  this feature is going beyond the projects scope dude.. even if we added a password to the shortend url other can access with the original url right

**Comment by shubhagarwal1** [comment]
@muruga21 i understand your concern, is there anything specific you are placning to implment i can work on that, all of th issues i have raised are ommited, so if ther is anyhting i can work on,it would be great to have an opportunity

**Comment by muruga21** [comment]
@shubhagarwal1 im sorry dude.. as your issue are been declined.. 

you can see ui is not proper.. there are scroll bars in the history page.. can you fix that.. 
i want to have no scroll bar..

can you work on this issue dude ?

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 im sorry dude.. as your issue are been declined..
> 
> you can see ui is not proper.. there are scroll bars in the history page.. can you fix that.. i want to have no scroll bar..
> 
> can you work on this issue dude ?

sure, i can work on that, should raise issue regarding that.
also @muruga21 can i have your discord account id, can we connect over there for better communincation

**Comment by muruga21** [comment]
@shubhagarwal1  I'm not very active on Discord. You can connect with me on LinkedIn or via email

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 im sorry dude.. as your issue are been declined..
> 
> you can see ui is not proper.. there are scroll bars in the history page.. can you fix that.. i want to have no scroll bar..
> 
> can you work on this issue dude ?

@muruga21 can you please tell me the exact problem with the scroll, can i move the qr section to the left adn review to the right to make it mor enhancing and clean
